[2025-03-11T18:09:17.869+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.transfer_backup manual__2025-03-11T18:09:06.609107+00:00 [queued]>
[2025-03-11T18:09:17.879+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.transfer_backup manual__2025-03-11T18:09:06.609107+00:00 [queued]>
[2025-03-11T18:09:17.879+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T18:09:17.879+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-03-11T18:09:17.880+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T18:09:17.893+0000] {taskinstance.py:1300} INFO - Executing <Task(SSHOperator): transfer_backup> on 2025-03-11 18:09:06.609107+00:00
[2025-03-11T18:09:17.898+0000] {standard_task_runner.py:55} INFO - Started process 10927 to run task
[2025-03-11T18:09:17.900+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project2', 'transfer_backup', 'manual__2025-03-11T18:09:06.609107+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/project2.py', '--cfg-path', '/tmp/tmplmf_iy2w']
[2025-03-11T18:09:17.900+0000] {standard_task_runner.py:83} INFO - Job 302: Subtask transfer_backup
[2025-03-11T18:09:17.955+0000] {task_command.py:388} INFO - Running <TaskInstance: project2.transfer_backup manual__2025-03-11T18:09:06.609107+00:00 [running]> on host 2ec744569db4
[2025-03-11T18:09:18.016+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project2
AIRFLOW_CTX_TASK_ID=transfer_backup
AIRFLOW_CTX_EXECUTION_DATE=2025-03-11T18:09:06.609107+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-11T18:09:06.609107+00:00
[2025-03-11T18:09:18.017+0000] {ssh.py:133} INFO - Creating ssh_client
[2025-03-11T18:09:18.041+0000] {ssh.py:111} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-03-11T18:09:18.049+0000] {base.py:73} INFO - Using connection ID 'ssh_vm' for task execution.
[2025-03-11T18:09:18.049+0000] {ssh.py:283} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-03-11T18:09:18.056+0000] {transport.py:1874} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-11T18:09:18.085+0000] {transport.py:1874} INFO - Authentication (password) successful!
[2025-03-11T18:09:18.086+0000] {ssh.py:460} INFO - Running command: scp -o StrictHostKeyChecking=no /tmp/backup_db.dump Wow-x@192.168.0.47:C:/Users/Wow-x/OneDrive/Desktop/
[2025-03-11T18:09:18.358+0000] {ssh.py:501} WARNING - Permission denied, please try again.
[2025-03-11T18:09:18.364+0000] {ssh.py:501} WARNING - Permission denied, please try again.
[2025-03-11T18:09:18.370+0000] {ssh.py:501} WARNING - Wow-x@192.168.0.47: Permission denied (publickey,password,keyboard-interactive).
[2025-03-11T18:09:18.372+0000] {ssh.py:501} WARNING - scp: Connection closed
[2025-03-11T18:09:18.394+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 171, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 159, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 152, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 255
[2025-03-11T18:09:18.398+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=project2, task_id=transfer_backup, execution_date=20250311T180906, start_date=20250311T180917, end_date=20250311T180918
[2025-03-11T18:09:18.408+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 302 for task transfer_backup (SSH operator error: exit status = 255; 10927)
[2025-03-11T18:09:18.433+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-03-11T18:09:18.451+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
