[2025-03-11T17:40:26.734+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.export_postgres manual__2025-03-11T17:40:15.870594+00:00 [queued]>
[2025-03-11T17:40:26.743+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.export_postgres manual__2025-03-11T17:40:15.870594+00:00 [queued]>
[2025-03-11T17:40:26.743+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T17:40:26.744+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-03-11T17:40:26.744+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T17:40:26.756+0000] {taskinstance.py:1300} INFO - Executing <Task(SSHOperator): export_postgres> on 2025-03-11 17:40:15.870594+00:00
[2025-03-11T17:40:26.760+0000] {standard_task_runner.py:55} INFO - Started process 7901 to run task
[2025-03-11T17:40:26.763+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project2', 'export_postgres', 'manual__2025-03-11T17:40:15.870594+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/project2.py', '--cfg-path', '/tmp/tmpbla8xucr']
[2025-03-11T17:40:26.763+0000] {standard_task_runner.py:83} INFO - Job 267: Subtask export_postgres
[2025-03-11T17:40:26.816+0000] {task_command.py:388} INFO - Running <TaskInstance: project2.export_postgres manual__2025-03-11T17:40:15.870594+00:00 [running]> on host 2ec744569db4
[2025-03-11T17:40:26.877+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project2
AIRFLOW_CTX_TASK_ID=export_postgres
AIRFLOW_CTX_EXECUTION_DATE=2025-03-11T17:40:15.870594+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-11T17:40:15.870594+00:00
[2025-03-11T17:40:26.878+0000] {ssh.py:133} INFO - Creating ssh_client
[2025-03-11T17:40:27.034+0000] {ssh.py:111} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-03-11T17:40:27.042+0000] {base.py:73} INFO - Using connection ID 'ssh_vm' for task execution.
[2025-03-11T17:40:27.043+0000] {ssh.py:283} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-03-11T17:40:27.051+0000] {transport.py:1874} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-11T17:40:27.082+0000] {transport.py:1874} INFO - Authentication (password) successful!
[2025-03-11T17:40:27.083+0000] {ssh.py:460} INFO - Running command: pg_dump -U postgres -F c -b -v -f /tmp/backup_db.dump postgres
[2025-03-11T17:40:27.317+0000] {ssh.py:501} WARNING - pg_dump:
[2025-03-11T17:40:27.318+0000] {ssh.py:501} WARNING -  error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"
[2025-03-11T17:40:27.340+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 171, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 159, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 152, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2025-03-11T17:40:27.344+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=project2, task_id=export_postgres, execution_date=20250311T174015, start_date=20250311T174026, end_date=20250311T174027
[2025-03-11T17:40:27.357+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 267 for task export_postgres (SSH operator error: exit status = 1; 7901)
[2025-03-11T17:40:27.376+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-03-11T17:40:27.400+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
