[2025-03-11T17:46:10.106+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.export_postgres manual__2025-03-11T17:46:00.357527+00:00 [queued]>
[2025-03-11T17:46:10.116+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.export_postgres manual__2025-03-11T17:46:00.357527+00:00 [queued]>
[2025-03-11T17:46:10.116+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T17:46:10.117+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-03-11T17:46:10.117+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T17:46:10.130+0000] {taskinstance.py:1300} INFO - Executing <Task(SSHOperator): export_postgres> on 2025-03-11 17:46:00.357527+00:00
[2025-03-11T17:46:10.135+0000] {standard_task_runner.py:55} INFO - Started process 8501 to run task
[2025-03-11T17:46:10.138+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project2', 'export_postgres', 'manual__2025-03-11T17:46:00.357527+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/project2.py', '--cfg-path', '/tmp/tmp0jrjnudi']
[2025-03-11T17:46:10.139+0000] {standard_task_runner.py:83} INFO - Job 275: Subtask export_postgres
[2025-03-11T17:46:10.195+0000] {task_command.py:388} INFO - Running <TaskInstance: project2.export_postgres manual__2025-03-11T17:46:00.357527+00:00 [running]> on host 2ec744569db4
[2025-03-11T17:46:10.262+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project2
AIRFLOW_CTX_TASK_ID=export_postgres
AIRFLOW_CTX_EXECUTION_DATE=2025-03-11T17:46:00.357527+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-11T17:46:00.357527+00:00
[2025-03-11T17:46:10.263+0000] {ssh.py:133} INFO - Creating ssh_client
[2025-03-11T17:46:10.293+0000] {ssh.py:111} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-03-11T17:46:10.302+0000] {base.py:73} INFO - Using connection ID 'ssh_vm' for task execution.
[2025-03-11T17:46:10.302+0000] {ssh.py:283} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-03-11T17:46:10.313+0000] {transport.py:1874} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-11T17:46:10.828+0000] {transport.py:1874} INFO - Authentication (password) successful!
[2025-03-11T17:46:10.829+0000] {ssh.py:460} INFO - Running command: pg_dump -U postgres -h localhost -p 5432 -F c -b -v -f /tmp/backup_db.dump postgres
[2025-03-11T17:46:11.033+0000] {ssh.py:501} WARNING - Password: 
[2025-03-11T17:46:11.040+0000] {ssh.py:501} WARNING - pg_dump: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: fe_sendauth: no password supplied
[2025-03-11T17:46:11.062+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 171, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 159, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 152, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2025-03-11T17:46:11.065+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=project2, task_id=export_postgres, execution_date=20250311T174600, start_date=20250311T174610, end_date=20250311T174611
[2025-03-11T17:46:11.075+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 275 for task export_postgres (SSH operator error: exit status = 1; 8501)
[2025-03-11T17:46:11.113+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-03-11T17:46:11.136+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
